### PR TITLE
feature/settings panel with sorting

### PR DESCRIPTION
**Pull request by jarlefosen**
Implemented settings panel which is collapsible.
The panel includes two features.
- Sort clicks by seconds left. See #34 
- Clear data.

See http://jarlefosen.github.io/thebutton_monitor/

### CODE REVIEW

**Comment by lezed1** [comment]
Sorry I've been slow to respond to this - finals will do that...

I like the simplistic settings panel, but here are my comments after trying it in the past day or so.

I noticed some weird behavior with the settings panel right after loading the page. It's x coordinate is too low, but then it fixes itself. (Side note: it's also too wide for my phone, Galaxy Note 3, which is wider than most.) That shouldn't be a problem, which leads me to my next comment.

I don't like the separate floating panel. I think a small settings icon (maybe even a unicode one: ⚙) either in the corner of the info panel, or the entire page which toggles the settings panel. I envisioned an icon directly to the right of the "Started" timestamp that switches the info panel to the settings panel, and back to info with another press. I think that would be much nicer than the current floating checkbox.

@jarlefosen, let me know what you think of this? If you don't want to implement it, I'd be happy to. If you don't get to it in the next day or so, I will definitely do something similar to that (after one more final!).

**Comment by lezed1** [comment]
Also, I think once the settings panel get finalized, a bunch of other issues and pull requests can be completed. #11, #18, #32 and #34 (like you mentioned) can be completed after this!

**Comment by jarlefosen** [comment]
I like your idea, an icon in the corner would be a better solution. Maybe not inside the info panel, but in the top right corner of the screen?

I'm up for finals as well, so I won't have time to work on it myself.

**Comment by lezed1** [comment]
I fixed a few things and I'm liking how the panel is looking so far. I have noticed that it's position when loading the page is incorrect, I'll look into that next.

**Pull request merged**
