### PR TITLE
Provide current counts of the different colors

### PR DESCRIPTION
**Pull request by gkotian**
Show the counts of the different colors along with the other stats.

### CODE REVIEW

**Comment by MiestrSpounk** [comment]
Wouldn't it make more sense and be cleaner to initialize the stats in the Stats structure?

**Comment by jamesrom** [comment]
I agree with @MiestrSpounk.

**Comment by gkotian** [comment]
>Wouldn't it make more sense and be cleaner to initialize the stats in the Stats structure?

Yup I agree. Removed the extra commit, and moved the initialization to the Stats structure.

**Comment by gkotian** [comment]
Closing as this is now obsolete.

**Pull request closed without merging**
