### PR TITLE
Modified chart.js to display the height of 60s clicks at 59.5s (so they have a height of 0.5s) so that hovering is easier.

### PR DESCRIPTION
**Pull request by wbernoudy**

### CODE REVIEW

**Comment by lezed1** [comment]
I'm testing this out now (just waiting for a 60s click :) ). I have thought about how to fix the hovering problem over a 60s click before, and I actually came up with another solution. I'd love to hear what you think about it.

My idea for how to fix the hovering was to have the bar hoverable as it is now, but then also add the height of the tooltip upwards as a hoverable area. This would mean that you could hover directly over each bar, or a bit above any bar to also display the tooltip. I like this idea because it would allow you to start hovering over any bar, and then move your mouse upwards over the tooltip without the content disappearing. 

@rhyzomatic, any thoughts on that idea versus yours (or a way to combine them)?

So after running yours for a bit, I have a few comments. First of all, I really like being able to see a purple bar that represents a 60s click where blank space once was. I do however find it slightly hard to quickly tell the difference between 59s and 60s. At first site (at least to me), it looks more then the 60s click is actually 59s and the 59s click is actually 58s. I've attached a screenshot with what I got from running locally for a few minutes.

60s Screen Shot

I think that the height of the 60s purple bar should be ~1px so it is just visible, but also conveys clearly that it shouldn't have any height ideally.

@rhyzomatic, I'd love to hear your thoughts on my few concerns.

**Comment by glasspusher** [comment]
Another way we could go about this, which I was going to try a while back, is to have the bar start out full and have the size shrink instead of grow.  This always seemed more intuitive to me.  This might be an easier way to implement this, maybe.  Thoughts?

**Comment by rhyzomatic** [comment]
I think making the 60s bar a certain amount of pixels high will be tough because as far as I can tell (someone feel free to correct me if otherwise) rendering is handled by d3 and is everything scaled to the dimensions of the page. One quick fix would be to reduce the height from what I have at 0.5 to something lower to that relatively it's still easy to differentiate. However, on small enough screens this might still be annoyingly small.

I also thought about having the tooltip appear when hovering over the space above the bar as well as on it. I am all for implementing this, but I think having the 60s clicks be more visible is still something that should be done.

Overall, I think @glasspusher's idea is the best. It solves this problem and is more intuitive. It's probably easier and cleaner to implement as well.

**Comment by lezed1** [comment]
You set an absolute height easily. Look at this line: https://github.com/rhyzomatic/jamesrom.github.io/commit/c9af624be3e3c49c7ab997e864eceb1310db7bc5#diff-e58c48f11bb0536ee6a67d24776f2112R116

Basically, where you called a function to calculate the size, you could just return a size. You would also have to do something similar on right line 124.

**Comment by lezed1** [comment]
That's what I had in mind - the bar is set to a forced height. I could flip the graph not too hard, but I would not merge that change without an OK from @jamesrom.

James, what do you think about it? I personally like the bar growing as the time since the last click goes, but I don't see why it couldn't be an option in the settings panel! (#37)

**Comment by rhyzomatic** [comment]
@lezed1 I'm not sure how I missed that, I think I got confused with the yPixel function. The absolute pixel height is definitely cleaner. 

Should I do anything with this pull request? (Sorry, I'm new to GitHub)

**Comment by lezed1** [comment]
@rhyzomatic I can't think of anything else for this pull request for you, I'm just going to see what @jamesrom wants to do with this (merge my commit, reverse everything in settings or both).

Also, I never would have known you are new to GitHub!

**Comment by jamesrom** [comment]
Thanks for contributing, I'm cleaning up this repo now (3 years later!)

**Pull request closed without merging**
