### PR TITLE
Median Click Time

### PR DESCRIPTION
**Pull request by voidref**
Add the median click time for the current view of the data.

### CODE REVIEW

**Comment by lezed1** [comment]
I merged this in locally and it worked perfectly! @jamesrom, want me to merge it in?

**Comment by lezed1** [comment]
I think this is ready to be merged in, it's working well!
@jamesrom Do you agree?

Here's a quick screenshot:
Screenshot

**Comment by jamesrom** [comment]
Yep looks good.

**Comment by legolas2000** [comment]
Why sort the array each time and not just iterate it and put the item in the correct position?
Much faster in the long run...

**Comment by lezed1** [comment]
@legolas2000 That's a good point! I'll make that change soon.

**Comment by voidref** [comment]
Sort() is unlikely to be implemented in javascript, it's probably native code in the interpreter.
Doing an insertion sort in javascript is probably going to be slower in the long run.
Sorting a sorted list is not a slow operation (unless it's implemented as a bubble sort, haha)

I would recommend testing to see if it's actually going to help or hurt perf on typical large data sets.

**Comment by lezed1** [comment]
I believe bubble sort would actually do quite well in this case (depending on the direction of the bubble). I will of course test, and I would also binary search to find the correct insertion point.

I might just change the storage to a length 60 array and just increment the corresponding index each time. I think that is the best solution, but I'll have to try them.

**Comment by voidref** [comment]
I agree that a binary search to do an insertion is going to be typically faster than an iteration, but then 1 line of code turns into a call out to a sort method. I'm just afraid it's a lot of work for something that may not really matter.

Isn't javascript typically 1/5 the speed of native even with the amazing JIT engines we are seeing these days?

Anyway, if you do have the time, this is an interesting exercise. I'd love to see the result of profiling, and perhaps you can write a blog post on it as a real world example for people of when it makes sense (or not?) to try and optimize something like this in JS!

**Comment by lezed1** [comment]
I'll probably just try the array of length 60. If that's not faster, I doubt the other methods would be.

**Comment by lezed1** [comment]
The solution with an array containing 60 values is very fast! A test sample with 100,000 clicks was processed in at most 1 ms. This is a constant time solution relative to the number of clicks (it technically varies with the number of possible discrete values).

**Pull request merged**
