### PR TITLE
Optional data truncating and Zoom & Pan QoL changes

### PR DESCRIPTION
**Pull request by MiestrSpounk**
Added an optional field to set a maximum amount of data points to keep.
For people who want to leave the site open but not end up with 10k data
points (it can lag up the graph a lot, and if you want to remove some you have to start at 0 again).
Demo: https://gfycat.com/WarmBeautifulAnura
- Keeps X data points + the timer bar
- Set to 0 to disable truncating (disabled by default)

Zoom & Pan QoL:
- New clicks will no longer compress the current zoomed section's bars
- Viewport will follow the zoomed section even if it moves due to data
  truncating

### CODE REVIEW

**Comment by MiestrSpounk** [comment]
Hey, it's me again!

I hope you don't mind me working on this too much, I really like your monitor and it's great to be able to improve it.

**Comment by jamesrom** [comment]
Hey, thanks for more contributions. I like this idea, but I think we should add a settings pane and make this option accessible there. I will set up the settings pane tonight and hopefully it wont be too hard to merge this in.

**Comment by MiestrSpounk** [comment]
Ah yes, that's definitely a better place to put it.

**Comment by bschoenfeld** [comment]
:+1: This is another feature I was hoping to see! Excellent project. Excellent contributors.

**Comment by jamesrom** [comment]
Hey @MiestrSpounk, I'm working on the settings panel. Still a work in progress, but you can see it here 815edd0ea91418991389a83da27996737582b34c.

The settings panel at the moment only has one setting (for a simple moving average feature I am working on). But it should be pretty easy to add more settings.

**Comment by lezed1** [comment]
This feature by no means has been implemented, but the ability to zoom in has been added! You can currently zoom in the see only a section of the data. If the newest section is being viewed, a similar result is achieved. New data always appears while only some is shown. This actually views a percentage of the data, not a set number.

Right now I don't see a real need for this feature, but I agree with @jamesrom that the option should go into a settings panel. I was going to work on reconnecting first and then add the settings panel. When I do that I'll merge this in too!

**Comment by jamesrom** [comment]
Thanks for contributing, I'm cleaning up this repo now (3 years later!)

**Pull request closed without merging**
