### PR TITLE
Simplify testing, define clicks and fmt

### PR DESCRIPTION
**Pull request by rdeforest**
* Make clicks global so it can be shared between Comms and Chart
* Define fmt in Comms
* Add http: to URLs to allow testing via file:///.../index.html

### CODE REVIEW

**Comment by jamesrom** [comment]
I just cleaned up a bunch of this cruft, this commit adds it back.

- `clicks` isn't used anywhere (it was used for stats, but now it's [done differently](https://github.com/jamesrom/jamesrom.github.io/blob/master/chart.js#L93))
- `fmt` is only used in Comms

I am happy to merge the URL changes, however.

**Comment by rdeforest** [comment]
Haha, I should have known you'd still be working on it. I'll pull your changes and submit a url-only pull request.

**Comment by rdeforest** [comment]
Derp, I see you already did merge the URL changes. Thanks :)

**Comment by jamesrom** [comment]
Haha, nope, I haven't. If you send me a PR with just the URL changes I'll merge it.

**Pull request closed without merging**
