### PR TITLE
Added number of each flair to stats

### PR DESCRIPTION
**Pull request by ratmatix**
Works well, maybe a choice for you to change to percent (e.g. Stats.f1 / max(Stats.resets, 1)) or maybe some better functions for it. It's a good stat to have though.

image

### CODE REVIEW

**Comment by ratmatix** [comment]
image

So the last commit did a moving average (3 resets) - Which I think is pretty cool.

However! I am a MAJOR d3 rookie (Seriously, this is my first attempt...) and I can't find the proper place to put the .remove() for the old moving average line -- You'll notice that it vanishes after the first tick update after a reset.

Was hoping you'd shed some light on it.

It's also taking the top-left coordinate of the rectangle as the path-point, with a tiny bit of work, can make it the middle of the top of the rectangle.

Hope i'm not bothering you with some contributions, it's more so I can learn too!

**Comment by jamesrom** [comment]
Contributions always welcome. I have been busy lately but I'll have a look tonight (AEST). Regarding the .remove() call, use the [General Update Pattern](http://bl.ocks.org/mbostock/3808218).

**Comment by bschoenfeld** [comment]
:+1: I was hoping for this exact enhancement. I was hoping for percentages instead of a count though.

**Comment by lezed1** [comment]
I believe this Pull Request has been completed already 
image

The comments have tended towards a simple moving average, which is exactly what #32 is referencing.

**Comment by jamesrom** [comment]
Yep, closed.

**Pull request closed without merging**
